---
volumes:
  dbdata:
  s3data:

services:
  db:
    env_file: .env
    image: postgres:17
    environment:
      PGDATA: /dbdata
      POSTGRES_DB: ${PEBBLE_DB_NAME}
      POSTGRES_USER: ${PEBBLE_DB_USER}
      POSTGRES_PASSWORD: ${PEBBLE_DB_PASSWORD}
    ports:
      - ${PEBBLE_DB_PORT}:5432
    volumes:
      - dbdata:/dbdata

  s3:
    env_file: .env
    image: minio/minio
    ports:
      - 9000:9000
    environment:
      MINIO_ROOT_USER: ${AWS_ACCESS_KEY_ID}
      MINIO_ROOT_PASSWORD: ${AWS_SECRET_ACCESS_KEY}
    command: server /data
    volumes:
      - s3data:/data
