---
volumes:
  dbdata:
  s3data:

services:
  db:
    env_file: .env
    image: postgres:17
    environment:
      PGDATA: /dbdata
      POSTGRES_DB: ${PEBBLE_DB_NAME}
      POSTGRES_USER: ${PEBBLE_DB_USER}
      POSTGRES_PASSWORD: ${PEBBLE_DB_PASSWORD}
    ports:
      - ${PEBBLE_DB_PORT}:5432
    volumes:
      - dbdata:/dbdata

  s3:
    env_file: .env
    image: minio/minio
    ports:
      - 9000:9000
    environment:
      MINIO_ROOT_USER: ${PEBBLE_S3_ACCESS_KEY_ID}
      MINIO_ROOT_PASSWORD: ${PEBBLE_S3_SECRET_ACCESS_KEY}
    command: server /data
    volumes:
      - s3data:/data

  s3-createbuckets:
    env_file: .env
    restart: no
    image: minio/mc
    environment:
      MC_HOST_S3: http://${PEBBLE_S3_ACCESS_KEY_ID}:${PEBBLE_S3_SECRET_ACCESS_KEY}@s3:9000
    depends_on:
      - s3
    entrypoint: >
      /bin/sh -c "
      while ! /usr/bin/mc ready s3; do
        echo 'Waiting for Minio...' && sleep 1;
      done; /usr/bin/mc mb myminio/${PEBBLE_S3_BUCKET_NAME}; exit 0;"
