[package]
name = "pebble-cli"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "pebble"
path = "./src/main.rs"

[dependencies]
pebble-server = { path = "../server" }

clap = { workspace = true, features = ["derive"] }
tokio = { version = "1.45.1", features = ["rt-multi-thread", "macros"] }
